apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: joshix2-joshix2-poi-map-app-dev
  annotations:
    argocd/app-name: joshix2-joshix2-poi-map-app-dev
    backstage.io/kubernetes-id: joshix2-joshix2-poi-map-app-dev
    backstage.io/kubernetes-namespace: joshix2
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=joshix2-joshix2-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/joshix2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/joshix2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/joshix2/deployments/joshix2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/joshix2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://joshix2-poi-map-app-joshix2.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/joshix"
  system: workshop-system-joshix2
  consumesApis:
    - gateway-api-joshix2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-joshix2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/joshix"
